---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: conv2pdf-depl
  labels:
    app: c2pdf
spec:
  selector:
    matchLabels:
      app: c2pdf
  replicas: 2
  template:
    metadata:
      labels:
        app: c2pdf
    spec:
      containers:
      - name  : c2pdf
        image : astitov/c2pdf:1.0
        ports :
        - containerPort: 80

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: c2pdf-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: conv2pdf-depl
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60

---
apiVersion: v1
kind: Service
metadata:
  name: c2pdf-service
  labels:
    env: test
spec:
  type: LoadBalancer
  selector:
    app: c2pdf
  ports:
    - name        : listener
      protocol    : TCP
      port        : 80
      targetPort  : 80
