name: convert2pdf

on:
  push:
  workflow_dispatch:

jobs:

  linters:
    runs-on: ubuntu-latest
    steps:

    - name: Make checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run super-linter
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

